# Generated by Django 6.0.3 on 2026-04-08 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("contact_info", models.TextField(blank=True, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("why_need_it", models.TextField(blank=True, null=True)),
                ("outreach_message", models.TextField(blank=True, null=True)),
                ("industry", models.CharField(blank=True, max_length=255, null=True)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("raw_response", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["industry", "location"],
                        name="leads_lead_industr_708bb8_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="leads_lead_created_921505_idx"
                    ),
                ],
            },
        ),
    ]
